### ISSUE TITLE
Failing to initialize solar power system in latest version

### ISSUE THREAD

**Issue by lordCONAN** [scottyphillips/echonetlite_homeassistant#195]
After updating to the latest version (3.8.4-beta1) I get the following error in my logs and my solar power system is no longer initializing.

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 17 September 2024 at 18:11:19 (2 occurrences)
Last logged: 05:48:39

Error setting up entry Solar Power System for echonetlite
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/echonetlite/__init__.py", line 317, in async_setup_entry
    await echonetlite.async_update()
  File "/config/custom_components/echonetlite/__init__.py", line 504, in async_update
    return await self.async_update_data(kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/echonetlite/__init__.py", line 537, in async_update_data
    batch_data = await self._instance.update(flags, no_request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychonet/EchonetInstance.py", line 150, in update
    response = await self._api.echonetMessage(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychonet/echonetapiclient.py", line 344, in echonetMessage
    await update_func(False)
  File "/config/custom_components/echonetlite/__init__.py", line 549, in async_update_callback
    await self.async_update_data(kwargs={"no_request": True})
  File "/config/custom_components/echonetlite/__init__.py", line 543, in async_update_data
    _LOGGER.debug(polling_update_debug_log(update_data, self._eojgc, self._eojcc))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/echonetlite/__init__.py", line 114, in polling_update_debug_log
    + f" - {get_name_by_epc_code(eojgc,eojcc,value)} {value:#x}({value}): {values[value]}\n"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/echonetlite/__init__.py", line 97, in get_name_by_epc_code
    _code = f"[{hex(jgc)}({jgc})-{hex(jcc)}({jcc})-{hex(code)}({code})]"
                                                    ^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer

**Comment by nao-pon** [comment]
@lordCONAN It seems that for some reason a run-time error occurred where a warning error message should have been generated.

The reason is that the following two parameters are not implemented, but are set to be used, causing a discrepancy. I will fix that.

- 0xA0: "Output power control setting 1",
- 0xA1: "Output power control setting 2",

**Comment by nao-pon** [comment]
@lordCONAN I believe I have fixed this. Please try Version 3.8.4-beta2.

**Comment by lordCONAN** [comment]
Just tried beta 2 and the same error is still coming up and it's unable to initialize the solar power system.

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 21:55:38 (2 occurrences)
Last logged: 21:57:09

Error setting up entry Solar Power System for echonetlite
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/echonetlite/__init__.py", line 317, in async_setup_entry
    await echonetlite.async_update()
  File "/config/custom_components/echonetlite/__init__.py", line 504, in async_update
    return await self.async_update_data(kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/echonetlite/__init__.py", line 537, in async_update_data
    batch_data = await self._instance.update(flags, no_request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychonet/EchonetInstance.py", line 150, in update
    response = await self._api.echonetMessage(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychonet/echonetapiclient.py", line 344, in echonetMessage
    await update_func(False)
  File "/config/custom_components/echonetlite/__init__.py", line 549, in async_update_callback
    await self.async_update_data(kwargs={"no_request": True})
  File "/config/custom_components/echonetlite/__init__.py", line 543, in async_update_data
    _LOGGER.debug(polling_update_debug_log(update_data, self._eojgc, self._eojcc))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/echonetlite/__init__.py", line 114, in polling_update_debug_log
    + f" - {get_name_by_epc_code(eojgc,eojcc,value)} {value:#x}({value}): {values[value]}\n"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/echonetlite/__init__.py", line 97, in get_name_by_epc_code
    _code = f"[{hex(jgc)}({jgc})-{hex(jcc)}({jcc})-{hex(code)}({code})]"
                                                    ^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer

**Comment by nao-pon** [comment]
I've tested it on https://github.com/KAIT-HEMS/elemu and there are no
issues on the emulator. Could you please provide the debug log for your
device? Please enable the debug log and restart HA to get the log.

**Comment by lordCONAN** [comment]
Sure, here's the debug log.

[home-assistant_echonetlite_2024-09-18T13-00-29.174Z.log](https://github.com/user-attachments/files/17050042/home-assistant_echonetlite_2024-09-18T13-00-29.174Z.log)

**Comment by nao-pon** [comment]
I checked the logs, but I still don't know the cause. I fixed it temporarily. Can you try the master version?

**Comment by lordCONAN** [comment]
The stable release is fine, it's only not setting up in the latest beta.

**Comment by lordCONAN** [comment]
Same problem with the master. Here's the debug log.

[home-assistant_echonetlite_2024-09-19T09-09-13.845Z.log](https://github.com/user-attachments/files/17056499/home-assistant_echonetlite_2024-09-19T09-09-13.845Z.log)

**Comment by nao-pon** [comment]
@lordCONAN I think I may have found the cause. If I'm right, this is a bug that has existed for some time and just happened to occur this time. I've released 3.8.4-beta3 which includes the fix, so please try it.

**Comment by lordCONAN** [comment]
beta3 is working fine for me. Awesome work!

**Comment by nao-pon** [comment]
@lordCONAN Your contribution helped us find and squash potential bugs! Thanks! 👍
